# Generated by Django 4.0.7 on 2022-09-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Client'), (2, 'Team_Member')], default='1'),
        ),
    ]
