openapi: 3.0.3
info:
  title: Your Project API
  version: 1.0.0
  description: Your project description
paths:
  /{id}/project-task/:
    get:
      operationId: project_task_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - project-task
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: project_task_create
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - project-task
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: project_task_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - project-task
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: project_task_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - project-task
      security:
      - tokenAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /client-project/:
    get:
      operationId: client_project_retrieve
      tags:
      - client-project
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: client_project_create
      tags:
      - client-project
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /create-member/:
    post:
      operationId: create_member_create
      tags:
      - create-member
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /create-user/:
    post:
      operationId: create_user_create
      tags:
      - create-user
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /general-teams/:
    get:
      operationId: general_teams_retrieve
      tags:
      - general-teams
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: general_teams_create
      tags:
      - general-teams
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /login/:
    post:
      operationId: login_create
      tags:
      - login
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthToken'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AuthToken'
          application/json:
            schema:
              $ref: '#/components/schemas/AuthToken'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
          description: ''
  /logout/:
    post:
      operationId: logout_create
      tags:
      - logout
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /project-detail/{id}/:
    get:
      operationId: project_detail_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - project-detail
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: project_detail_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - project-detail
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: project_detail_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - project-detail
      security:
      - tokenAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /task-detail/{id}/:
    get:
      operationId: task_detail_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - task-detail
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: task_detail_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - task-detail
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: task_detail_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - task-detail
      security:
      - tokenAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /team-details/{id}/:
    get:
      operationId: team_details_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - team-details
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: team_details_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - team-details
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
    delete:
      operationId: team_details_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - team-details
      security:
      - tokenAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /user/profile/:
    get:
      operationId: user_profile_retrieve
      tags:
      - user
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: user_profile_update
      tags:
      - user
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  schemas:
    AuthToken:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        token:
          type: string
          readOnly: true
      required:
      - password
      - token
      - username
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
